sudo: false
dist: xenial
language: Rust

rust:
- stable
- beta
- nightly

env:
  global:
    - PATH="$HOME/.cargo/bin:$PATH"
    - RUST_BACKTRACE=1

git:
  depth: false

cache:
  directories:
    - $HOME/.cargo/bin
    - $TRAVIS_BUILD_DIR/target
install:
- ci/travis/rust/install.sh

script:
- ci/travis/rust/script.sh

after_script:
- curl -SsL "https://codecov.io/bash" | bash

after_success:
- ci/travis/rust/after_success.sh

notifications:
  email:
  - althonosdev@gmail.com
