sudo: false
dist: xenial

env:
  global:
    - PATH="$HOME/.cargo/bin:$PATH"
    - RUST_BACKTRACE=1
    - RUSTC_WRAPPER=sccache
    - SCCACHE_DIR="$HOME/.cache/sccache"

stages:
  - name: Rust
  - name: Python

.test-rust: &test-rust
  stage: Rust
  language: rust
  cache:
    directories:
      - $SCCACHE_DIR
      - $HOME/.cargo
  before_install:
    - ci/travis/setup.sh
  script:
    - cargo tarpaulin -v -p fastobo --out Xml --ciserver travis-ci
  after_script:
    - curl -SsL "https://codecov.io/bash" | bash

.test-python: &test-python
  stage: Python
  language: python
  cache:
    directories:
      - $SCCACHE_DIR
      - $HOME/.cargo
      - $HOME/.cache/pip
      - $TRAVIS_BUILD_DIR/target
  services:
    - docker
  before_install:
    - ci/travis/setup.sh
  before_script:
    - python setup.py build_ext --inplace
  script:
    - python setup.py test

jobs:
  include:
    # - rust: stable
    #   <<: *test-rust
    # - rust: beta
    #   <<: *test-rust
    # - rust: nightly
    #   <<: *test-rust
    # - python: 3.5
    #   <<: *test-python
    # - python: 3.6
    #   <<: *test-python
    - python: 3.7
      after_success:
        - ci/travis/deploy.sh
      <<: *test-python

# deploy:
#   provider: script
#   script: ci/travis/deploy.sh
#   on:
#     tags: true
#     repo: althonos/fastobo
#     rust: stable

notifications:
  email:
  - althonosdev@gmail.com
