sudo: false
dist: xenial

env:
  global:
    - PATH="$HOME/.cargo/bin:$PATH"
    - RUST_BACKTRACE=1
    - RUSTC_WRAPPER="$HOME/.cargo/bin/sccache"
    - SCCACHE_DIR="$HOME/.cache/sccache"

git:
  depth: false

stages:
  - name: Rust
  - name: Python
  - name: Python on OSX

.test-rust: &test-rust
  stage: Rust
  language: rust
  cache:
    directories:
      - $SCCACHE_DIR
      - $HOME/.cargo
  install:
    - ci/travis/setup.sh
  script:
    - cargo tarpaulin -v -p fastobo --out Xml --ciserver travis-ci
  after_script:
    - curl -SsL "https://codecov.io/bash" | bash

.test-python: &test-python
  stage: Python
  language: python
  env:
    - PYTHON=python
  cache:
    directories:
      - $SCCACHE_DIR
      - $HOME/.cargo
      - $HOME/.cache/pip
      - $HOME/Library/Caches/Homebrew
      - $TRAVIS_BUILD_DIR/target
  services:
    - docker
  install:
    - ci/travis/setup.sh
  before_script:
    - python setup.py build_ext --inplace
  script:
    - python setup.py test
  before_cache:
    - brew cleanup
  after_success:
    - ci/travis/deploy.sh

.test-python-osx: &test-python-osx
  stage: Python on OSX
  os: osx
  language: generic
  cache:
    directories:
      - $SCCACHE_DIR
      - $HOME/.cargo
      - $HOME/.cache/pip
      - $TRAVIS_BUILD_DIR/target
  install:
    - ci/travis/setup.sh
  before_script:
    - python3 setup.py build_ext --inplace
  script:
    - python3 setup.py test
  after_success:
    - ci/travis/deploy.sh

jobs:
  include:
    - rust: stable
      <<: *test-rust
    - rust: beta
      <<: *test-rust
    - rust: nightly
      <<: *test-rust
    - python: 3.5
      <<: *test-python
    - python: 3.6
      <<: *test-python
    - python: 3.7
      <<: *test-python
    - env: PYTHON=python3.6
      <<: *test-python-osx
    - env: PYTHON=python3.7
      before_install:
        - brew unlink python
        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/python.rb
      <<: *test-python-osx

notifications:
  email:
  - althonosdev@gmail.com
