[package]
name = "fastobo"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

[dependencies.pest]
version = "2.1.0"
[dependencies.pest_derive]
version = "2.1.0"
[dependencies.failure]
version = "*"

# Used for obo14::IRI
[dependencies.iri-string]
version = "*"
default-features = false

[dev-dependencies.textwrap]
version = "*"
[dev-dependencies.difference]
version = "*"
[dev-dependencies.tests-macros]
path = "./tests-macros"


[dependencies.pyo3]
version  = "0.6.0-alpha.4"
optional = true
features = ["extension-module"]
