[package]
name = "ontology"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

[dependencies]
nom = "*"
chrono = { version  = "*", default-features = false }
