[package]
name = "ontology"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

[dependencies]
failure = "*"

[dependencies.chrono]
version = "*"
default-features = false

[[test]]
path = "tests/lib.rs"
name = "tests"
