[workspace]
members = ["fastobo-syntax"]

[lib]
path = "fastobo/lib.rs"

[package]
name = "fastobo"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

# Required dependencies
[dependencies]
pest = "2.1.0"
failure = "0.1.5"
url = "1.7.2"
fastobo-syntax = { path = "./fastobo-syntax", version = "0.1.0" }

[dev-dependencies]
reqwest = "*"
lazy_static = "1.3.0"
obofoundry = "*"
pretty_assertions = "*"
serde_yaml = "*"

[profile.bench]
lto = true

[profile.release]
lto = true
