[workspace]
members = ["fastobo-syntax", "fastobo-py/fastobo"]

[package]
name = "fastobo"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"
license = "MIT"
description = "Faultless AST for Open Biomedical Ontologies."
repository = "https://github.com/althonos/fastobo"
readme = "README.md"
keywords = ["obo", "ontology", "obofoundry", "ast", "syntax", "parser"]
categories   = ["science", "parser-implementations"]

[package.metadata.docs.rs]
features = ["docs"]

[lib]
name = "fastobo"
path = "fastobo/lib.rs"

[[bin]]
name = "validate"
path = "fastobo/bin/validate.rs"

[badges.travis-ci]
repository = "althonos/fastobo"
[badges.codecov]
repository = "althonos/fastobo"
service    = "github"
[badges.is-it-maintained-issue-resolution]
repository = "althonos/fastobo"
[badges.maintenance]
status     = "actively-developed"

[dependencies]
pest = "2.1.0"
failure = "0.1.5"
url = "1.7.2"
fastobo-syntax = { path = "./fastobo-syntax", version = "0.1.0" }
opaque_typedef = "0.0.5"
opaque_typedef_macros = "0.0.5"

[dev-dependencies]
reqwest = "0.9.12"
lazy_static = "1.3.0"
obofoundry = "0.1.2"
pretty_assertions = "0.6.1"
serde_yaml = "0.8.8"

[profile.bench]
lto = true

[profile.release]
lto = true
