[package]
name = "fastobo"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

# Required dependencies
[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
failure = "0.1.5"
url = "1.7.2"

[dev-dependencies]
textwrap = "0.11.0"
difference = "2.0.0"
[dev-dependencies.tests-macros]
path = "./tests-macros"

[profile.bench]
lto = true

[profile.release]
lto = true
