[package]
name = "fastobo-derive"
version = "0.3.0"
authors = ["Martin Larralde <martin.larralde@ens-paris-saclay.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
darling = "*"
syn = "0.15"
heck = "*"
quote = "*"
