[package]
name = "fastobo-py-derive"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-cachan.fr>"]
edition = "2018"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "0.15.30"
quote = "0.6.12"
