[package]
name = "fastobo2owl"
version = "0.1.0"
authors = ["Martin Larralde <martin.larralde@ens-cachan.fr>"]
edition = "2018"
workspace = ".."

[dependencies]
fastobo = { path = "../fastobo" }
horned-owl = "0.5.0"
failure = "*"
curie = "*"
either = "*"
